version: '3.8'

services:
  KNL_NL_Coding-Challenge_SFMovies.Server:
    build:
      context: ./WebAPI
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - app-network

  knl_nl_coding-challenge_sfmovies.client:
    build:
      context: ./ClienteAngular
    ports:
      - "4200:80"
    depends_on:
      - webapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge