version: '3.8'

services:
  server:
    build:
      context: ./KNL_NL_Coding-Challenge_SFMovies.Server
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - app-network

  client:
    build:
      context: ./knl_nl_coding-challenge_sfmovies.client
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge